document.writeln(" ");
document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"zh-CN\">");
document.writeln("  <head>");
document.writeln("    <title>直通车官网</title>");
document.writeln("    <meta charset=\"UTF-8\"/>");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />");
document.writeln("    <meta name=\"keywords\" content=\"美贝官网\">");
document.writeln("<meta name=\"description\" content=\"美贝官网\">");
document.writeln("<meta name=\"csrf-param\" content=\"token\">");
document.writeln("");
document.writeln("<link href=\""+actx+"/webjars/bootstrap/3.3.2/css/bootstrap.min.css\" rel=\"stylesheet\">");
document.writeln("<link href=\""+actx+"/webjars/jquery-ui/1.11.2/jquery-ui.min.css\" rel=\"stylesheet\">");
document.writeln("<link href=\""+actx+"/css/login/common.css\" rel=\"stylesheet\">");
document.writeln("<link href=\""+actx+"/css/login/mbindex.css\" rel=\"stylesheet\">");
document.writeln("<script src=\""+actx+"/webjars/bootstrap/3.3.2/js/bootstrap.min.js\"></script>");
document.writeln("<script src=\""+actx+"/webjars/jquery-ui/1.11.2/jquery-ui.js\"></script>");
document.writeln("<script src=\""+actx+"/js/login/jquery.ui.datepicker-zh-CN.js\"></script>");
document.writeln("");
document.writeln("");
document.writeln("  </head>");
document.writeln(" <body class=\"navbar-padding-top\">");
document.writeln("  <!--header_begin-->");
document.writeln("  <nav class=\"navbar navbar-default navbar-fixed-top active\" role=\"navigation\">");
document.writeln("      <div class=\"container\">");
document.writeln("        <div class=\"navbar-header\">");
document.writeln("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">");
document.writeln("            <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("            <span class=\"icon-bar\"></span>");
document.writeln("            <span class=\"icon-bar\"></span>");
document.writeln("            <span class=\"icon-bar\"></span>");
document.writeln("          </button>");
document.writeln("          <a class=\"navbar-brand\" href=\"javascript:void(0)\"><img src=\""+actx+"/images/index_new/logo.png\" title=\"美贝直通车\"/></a></div>");
document.writeln("        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.writeln("        <ul class=\"nav navbar-nav\"><li role=\"presentation\"><a href=\""+ctx+"/channel/index.mbay\">首页 <span class=\"sr-only\">(current)</span></a></li>");
document.writeln("<li role=\"presentation\"><a href=\""+ctx+"/channel/index.mbay#chanpin\">产品介绍</a></li>");
document.writeln("<li role=\"presentation\"><a href=\""+ctx+"/channel/index.mbay#hezuo\">合作伙伴</a></li>");
document.writeln("<li role=\"presentation\"><a href=\""+ctx+"/channel/index.mbay#contact\">联系我们</a></li>");
document.writeln("</li></ul><ul class=\"nav navbar-nav navbar-right\"><li role=\"presentation\"><a href=\""+ctx+"/channel/toLogin.mbay\">登录</a></li>");
document.writeln("<li role=\"presentation\"><a href=\""+ctx+"/signup/enterprise.mbay\">注册</a></li>");
/*document.writeln("<li role=\"presentation\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" role=\"button\" aria-expanded=\"false\" href=\"javascript:;\"><span class=\"name ellipsis\">个人中心</span> <span class=\"caret\"></span></a>");*/
document.writeln("");
document.writeln("</li>");
document.writeln("</ul>       </div><!-- /.navbar-collapse -->");
document.writeln("      </div><!-- /.container -->");
document.writeln("    </nav><!-- /nav -->");
document.writeln("  <!--header_end-->");
document.writeln("");
document.writeln("    ");
document.writeln("  <nav style=\"margin-top:30px;\">");
document.writeln("  </nav>");
document.writeln("  </body>");
document.writeln("");